# Generated by Django 5.2.11 on 2026-02-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reading date')),
                ('status', models.CharField(choices=[('S', 'Started'), ('P', 'In Progress'), ('C', 'Completed')], default='S', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
